### ISSUE TITLE
Axiom to only run rule on projects with a lot of contributors

### ISSUE THREAD

**Issue by yannjor** [todogroup/repolinter#169]
I have been thinking it would be cool to have an axiom to apply rules only on projects with a lot of contributors (e.g. >20). For example the "contributing-file-exists" or "code-of-conduct-file-exists" rules might not be very important for small projects with only one or a few developers, but would be nice to have on larger projects. 

I was thinking this could be implemented using for example the GitHub API to get the number of contributors, although this would only work for GitHub projects. It would also obviously require internet access, which might not be desirable.

Any comments or ideas?

**Comment by BigBlueHat** [comment]
Interesting idea!

Code's of Conduct and Contributing files, however, are preemptive and best suited for projects with only one developer who's hoping for more involvement. The number of people involved doesn't signal the need for either of those...though it does highlight the extent risk for projects that don't have them!

There may be other things that could be built around (previous) contributor numbers, but those should ideally be kept optional so that the project can continue to work on non-GitHub hosted repositories.

**Comment by yannjor** [comment]
Thanks for your comments! Another way this could maybe be implemented is by looking at the commits to the target repository (e.g. git log) and somehow figuring out how many different contributors there are there. What do you think about this approach?

What do you mean by the feature being kept optional? Aren't the axioms always optional to use?
