### ISSUE TITLE
Ideas for new rules

### ISSUE THREAD

**Issue by Lucas-C** [todogroup/repolinter#39]
Hello,

Instead of creating one issue for each, I thought it would be simpler to gather those ideas and ask for feedback in one issue:

- check for the existence of the following files:
  * `CONTRIBUTING.md`
  * `CHANGELOG.md`

- check that issues are enabled in the repo, or else that there is a Contact section in the README

- suggest to add Github tags if none exists

- if the repo contains mainly python files, suggest to add a `setup.py`.
Same for NodeJS and a `package.json`

- finally, I would love a **check for a "Screenshots" or "Demo" section in the README it the repo contains HTML (template) files**. The rationale is that it serves the project visibility a LOT to include pictures. Of course it makes a lot less sense for pure code libraries. And checking for images links in the README is not a good solution as it could be a logo.

**Comment by sschuberth** [comment]
I believe it would make more sense to track these ideas individually. Otherwise it's hard to track which have been implemented so far, and which not yet.

Anyway, some feedback:

* There already is a `contributing-file-exists` rule.

* Checking whether issues are enabled in the repo would require an online connection. So far repolinter is working completely offline, e.g. by running [licensee](https://github.com/benbalter/licensee) locally instead of querying the [licenses API](https://developer.github.com/v3/licenses/), and personally I actually like that philosophy.

* Likewise for GitHub tags. But maybe we could introduce a special `online` rule set?

* About suggesting to add package manager files, I don't think you can judge just from the language that the code actually represents a package. It could be something else, like a loose collection of code snippets.

**Comment by Lucas-C** [comment]
Ok, thanks for you feedback !

Globally, I agree with your answer.
But yes, it may be interting to call online APIs at some point, otherwise this linter may be limited.

So, so far, only the `CHANGELOG.md` check rule may be worthwhile to implement ?

I can close this ticket and create a new one for that rule.

**Comment by hyandell** [comment]
I think it would be in rulesets/default.json (or some other example file):

      "contributing-file-exists:file-existence": ["warning", {"files": ["CHANGELOG*"]}],

PRs welcome :)

On the online vs offline; I think it would be good to have online rules, but they would indicate they were online and the tool would skip them if offline (the same way it skips if linguist unavailable etc).

Possible we could have an Axiom of "Can see GitHub" etc, and rules that would descend from there (referring to a separate issue #59 where I mentioned the Axiom idea :) ).

(Closing this)
