### ISSUE TITLE
The ruleset test-directory-exists is case sensitive and searches only in main directory

### ISSUE THREAD

**Issue by sandhraprakash** [todogroup/repolinter#67]
- [x] 1. The ruleset that checks whether tests directory exists or not is case sensitive.
    If one has "Tests" folder instead or "tests". the ruleset fails.
 - [x] 2. There was a condition where the said tests folder was in one of the subdirectories and not in the parent directory. In such a situation the ruleset again failed

**Comment by adamdmharvey** [comment]
@sandhraprakash, just helpig out because I recently got a little more into these rules as well.

1. I think you are right, the test is case sensitive. Easy workaround would be to specify both tests and Tests.
2. Since directory-exists works like file-exists, you should be able to use the same covention that the other rules use, i.e. just put `**/tests` and I bet it would work for any sub-folder?

**Comment by hyandell** [comment]
Agreed.

It could change to cover all the various defacto standards for test directories, but I think we should only change if there's proof it's a defacto standard (ie: Maven's src/tests/ style approach)

**Comment by sandhraprakash** [comment]
Yes, understood, the directory-location-part of it. 
But what about the case sensitive rule. Agreed, I can tweak it in my local to make it case insensitive (Personally I am not familiar with the language used or code.). Is it part of any standard or can we correct this in the original source code?
