### ISSUE TITLE
Standard check for license info in 'first 5 lines' should check for SPDX-License-Identifier

### ISSUE THREAD

**Issue by kpfleming** [todogroup/repolinter#81]
Source files which specify their license in this form:
```
SPDX-License-Identifier: MIT
```

(in a suitable comment style for the language used in the file) should *pass* the license information check.

**Comment by bufferoverflow** [comment]
this should be covered by https://github.com/todogroup/repolinter/commit/3739198e891d380efc3b3cdb72677eec9adca2b9 

did you use repolinter npm package (this commit is missing there) or from source?

**Comment by kpfleming** [comment]
I wasn't running, it actually, @trevmex was and was showing us the output.

**Comment by hyandell** [comment]
Agreed that the default ruleset should cover this.

A more specific example would also be good if only the SPDX identifier is wanted.

**Comment by kestewart** [comment]
Any update on this?    More and more projects have adopted the one line license identifiers in their files, and it would be good to be able to point to the repolinter as a tool to use - but this failing is causing problems.   Documentation needs to be updated as well.

**Comment by prototypicalpro** [comment]
The default ruleset currently looks for the following header, which includes a SPDX identifier:
```javascript
// Copyright <year> <company>. All rights reserved.
// SPDX-License-Identifier: <licence>
```
This rule is shown below:
https://github.com/todogroup/repolinter/blob/9f0f47169ab2940873ac6e726c42876838c235f7/rulesets/default.json#L152-L163
This rule could be modified to the following to only support SPDX license headers:
```javascript
[
  "source-license-headers-exist": {
      "level": "warning",
      "rule": {
        "type": "file-starts-with",
        "options": {
          "globsAll": ["**/*.js", "!node_modules/**"],
          "lineCount": 5,
          "patterns": ["SPDX-License-Identifier"],
          "flags": "i"
        }
      }
    },
  }
]
```
Since this issue is pretty old I don't think this issue warrants changing the default ruleset, but if anyone would still like to see the default ruleset modified with this change please feel free to leave a comment suggesting it.
