### ISSUE TITLE
Request for Group/Org-level scanning

### ISSUE THREAD

**Issue by kristakhare** [todogroup/repolinter#91]
Thanks so much for this awesome tool! One thing that would make it even more amazing would be to add group or org-level scanning to check multiple repos in the same org.

**Comment by hyandell** [comment]
I think that should be a separate tool, but I'm +1 on the idea. In essence it's a 'run repolinter N times and collate'. Also my feeling is to try to avoid repolinter becoming a github only and/or online required tool.

**Comment by jwsloan** [comment]
@hyandell are you against repolinter being used in a GitHub app? Or you just don't want it to be ONLY GitHub? I've just started on a Probot app for repolinter...

**Comment by prototypicalpro** [comment]
To add to this issue two years later, at New Relic we use [repolinter-action](https://github.com/newrelic/repolinter-action) to integrate repolinter with our organization, which works for both a centralized (one repository scanning the entire org) and decentralized (each repository scanning itself). I can also recommend [googleapis/github-repo-automation](https://github.com/googleapis/github-repo-automation) for automatically opening PRs on a large number of repositories.

Since this issue is pretty old and scanning multiple repositories is most likely out of scope for repolinter itself, I'm going to go ahead and close this issue. Feel free to leave a comment if there are still concerns.

**Comment by christianherweg0807** [comment]
@prototypicalpro : could you share your workflow, to run the linter against all organization repositories?

that would be great... thank you
